fix a few typo's in README.md file
drduh/macOS-Security-and-Privacy-Guide pull request #423
Opened 2023-04-26 03:02 UTC by Jeff-Meendering

Looked through the README file and found a few typos.  Just cleaned a few things up.

2023-08-13 20:04 UTC, drduh commented
Can you remove the additional files which got included?

2023-08-15 03:35 UTC, Jeff-Meendering commented
Alright, I've just removed the additional files... Please let me know if there are any other changes needed.

2023-08-29 04:39 UTC, blochberger requested changes
Spotted two minor mistakes. Looks good otherwise.

2023-08-29 04:39 UTC, blochberger commented on README.md
> +For acomparison to Windows 10, see <https://fix10.isleaked.com/>
Missing space.

2023-08-29 04:39 UTC, blochberger commented on README.md
> +  * [Network](#network)This
Left "This" here on accident?

2023-09-14 14:47 UTC, closed without merging